apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.targetPort }}
          env:
            - name: PORT
              value: "{{ .Values.app.targetPort }}"
            - name: NATS_URL
              value: {{ .Values.nats.url }}
            - name: POSTGRES_URL
              value: {{ .Values.postgres.url }}            

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  selector:
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.port}}
      targetPort: {{ .Values.app.targetPort}}

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: {{ .Release.Name }}-configmap
# data:
#   myvalue: "Hello World"
#   drink: {{ .Values.app.name }}
