image: kerituni12/submission:1.1
pullPolicy: Always
storageClassName: longhorn
postgres:
  url: postgresql://eadmin:Random123%40@edicode.dev:5432/submission
nats:
  url: "nats://nats.nats:4222"
app:
  name: submission
  port: 3003
