name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master
      # Install Pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: "7.x"
      # Install Node.js
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "pnpm"
      # Install workspace dependencies
      - name: Install dependencies
        run: pnpm install

      - run: pnpm nx workspace-lint
      - run: pnpm nx format:check
      - run: pnpm nx affected --target=lint --parallel=3
      - run: pnpm nx affected --target=test --parallel=3 --ci --code-coverage
      - run: pnpm nx affected --target=build --parallel=3
